# Generated by Django 2.2.10 on 2020-06-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relations',
            name='main',
        ),
    ]
