# Generated by Django 2.2.10 on 2020-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_relations_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='main',
            field=models.BooleanField(default=1, verbose_name='Главная тема'),
            preserve_default=False,
        ),
    ]
